server:
  port: 9090
  # TODO: 设置 Tomcat 最大单次请求大小
  tomcat:
    max-http-form-post-size: 200MB
  # TODO: 设置 undertow 最大单次请求大小
  undertow:
    max-http-post-size: 200MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # TODO: 修改数据库信息 (url、username、password)
    url: jdbc:mysql://localhost:3306/subway_clean?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: yangao
    password: nswdfq
  profiles:
    active: dev
  redis:
    # TODO: 修改 redis 配置信息 (password、host、port)
    password: nswdfq
    host: localhost
    port: 6379
    client-type: lettuce
  servlet:
    multipart:
      # TODO: 设置单个文件最大大小
      max-file-size: 200MB
      # TODO: 设置单次请求最大大小
      max-request-size: 200MB
# swagger 配置
open-api:
  # 文档信息
  info:
    # 文档标题
    title: swagger3文档
    # 文档描述
    description: 什么时候努力都不晚除了一会儿
    # 文档版本
    version: 1.0.0
    # 许可证信息
    license:
      # 许可证名称
      name: Apache 2.0
      # 许可证地址
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    # 文档联系人信息
    contact:
      # 姓名
      name: 杨奥
      # 主页
      url: https://github.com/YangAoLib
      # 邮箱, 用于发送邮件
      email: ya1398789131@163.com
  # 服务器信息(运行路径)
  servers:
    - url: http://localhost:9090  # 地址
      description: 开发环境  # 描述
    - url: http://unknown:9090
      description: 其他环境
    - url: http://10.20.112.222:9090
      description: 校园网
# mybatis plus 配置
mybatis-plus:
  type-aliases-package: edu.yangao.entity
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: deleted
# modbus 配置
modbus:
  # TODO: 地址与端口信息修改 (ip、port)
  # 从机地址
  ip: test.gamehu4399.top
  # 端口
  port: 48535
  # 从机id
  slave-id: 1
# 文件工具配置
file-util:
  # TODO: 文件存储位置
  storage-path: /home/root/file/
  redis-dir: file

---
spring:
  config:
    activate:
      # 多环境配置
      on-profile: dev
  redis:
    password: nswdfq
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 9090
  tomcat:
    max-http-form-post-size: -1
  undertow:
    max-http-post-size: -1
# modbus 配置
modbus:
  # 从机地址
  ip: localhost
  # 端口
  port: 502
  # 从机id
  slave-id: 1
# 文件工具配置
file-util:
  storage-path: C:/software/upload-file/
